// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2JV1G_z3N9k22B2T3yJqw71VmBUiq3ss',
    appId: '1:321028611367:web:850eb6d66d3724daec1d02',
    messagingSenderId: '321028611367',
    projectId: 'thesaurus-3adb2',
    authDomain: 'thesaurus-3adb2.firebaseapp.com',
    storageBucket: 'thesaurus-3adb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjr0IuxQGtBAHIH5NKuZ6UJxtvBldXNgE',
    appId: '1:321028611367:android:7a28f2df3595acd2ec1d02',
    messagingSenderId: '321028611367',
    projectId: 'thesaurus-3adb2',
    storageBucket: 'thesaurus-3adb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYemNlBoYhi6WY5zsKxl2k_wjzCNWaXzM',
    appId: '1:321028611367:ios:4ae9efce3521b90bec1d02',
    messagingSenderId: '321028611367',
    projectId: 'thesaurus-3adb2',
    storageBucket: 'thesaurus-3adb2.appspot.com',
    iosClientId: '321028611367-6llajsog4hpodfkgmtdbv733152qe71m.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesaurus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYemNlBoYhi6WY5zsKxl2k_wjzCNWaXzM',
    appId: '1:321028611367:ios:4ae9efce3521b90bec1d02',
    messagingSenderId: '321028611367',
    projectId: 'thesaurus-3adb2',
    storageBucket: 'thesaurus-3adb2.appspot.com',
    iosClientId: '321028611367-6llajsog4hpodfkgmtdbv733152qe71m.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesaurus',
  );
}
