name: authentication_repository

environment:
  sdk: '>=2.18.2 <3.0.0'


dev_dependencies:
  flutter_lints: ^2.0.0

  
dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.1.2
  google_sign_in: ^5.3.2